poetry.lock, procollab_skills/settings.py, pyproject.toml
=> cors again

apps/courses/admin.py, apps/questions/models/questions.py
1. Добавил необходимое поле "тип единицы задачи".
2. Добавил перевод в заголовке.
3. Чуть-чуть поправил verbose_name у модели (была опечатка)
=> Админка - "Части задачи"

apps/questions/views/answers.py
1. Исправлена логика проверки:
**Правки в response не вносились, все осталось идентично, просто исправлены ошибки, например в случае id не из этой задачи.**
-Если даны правильные ответы (но не все), отправляется: "need more...".   
-Если в ответе будут неправильные ответы/id вообще не отсюда, отправляется: "wrong_answers" со списком неправильных id (исключая правильные, если они были).   
-Если даны ответы полностью совпадающие с ожидаемыми: "success"
2. Оптимизация:   
-Кол-во запросов к БД сократилось с 4х до 1го.  
-Реализация через set ускоряет проверку.  
-Упрощена реализация.
=> Правки в логику проверки QuestionExcludePost

.github/workflows/deploy-cd.yml
Для того чтобы работало, необходим доступ по SSH  на сервере.
Я пока боюсь ковыряться, на тестовом личном все прошло успешно.
1. В конфиге указан pull origin main, но на сервере ветка называется master, посмотри, пожалуйста, ок ли это.
2. У меня нет доступов к секретам репозитория, в лс скину наименования которые необходимо установить.
3. Пока не могу сказать заведется ли, уточнения все скину в ЛС.
На личном VPS похожий конфиг завелся и работает, тут скорее всего необходимо внести правки (подробнее в ЛС)
=> ci-cd to dev server

apps/progress/filters.py, apps/progress/serializers.py
исправлен баг, что ломались рейтинги если юзер не заполнил возраст
=> age bug fixed

apps/procollab_skills/auth.py
=> hotfix skills current user

apps/courses/serializers.py, apps/courses/views.py, apps/questions/api_examples.py, apps/questions/serializers.py, apps/questions/typing.py, apps/questions/views/answers.py
1. Лишние сериализаторы удалены.
2. Нужные сериализаторы частично переписаны.
3. Во вьюхах поправлены сериализаторы - некорректные заменены.
4. Добавлены api examples в доку для удобства работы
Все типы вопросов протестированы локально, ответы и информация по вопросам дергаются и отправляются по аналогичной предыдущей схеме
=> Рефакторинг сериализаторов (questions app) + примеры response api (questions app)

apps/courses/views.py
Поле skill_name добавлено в response TaskStatsGet
=> Добавление поля skill_name

apps/subscription/views.py
=> fixed bug for buying subscriptions2

apps/courses/managers.py, apps/courses/models.py, apps/courses/services.py, apps/courses/utils/get_skill_level.py, apps/courses/views.py, apps/progress/services.py, apps/progress/views/profile.py, apps/progress/views/rating.py
- Менеджер добавлен
- Внесены правки в запросы: чтобы был учтен статус
- Поправлены запросы которые возвращали 500, вместо 404
=> Модельный менеджер для Skill - для только опубликованных навыков

apps/questions/admin.py
Добавлены поля отображения в списках вопросов:
- ID,  
- Описание,  
- ID части задачи,  
- Навык к которому относится вопрос;
=> Правки в админ панель для удобства заполнения

apps/progress/serializers.py
=> fixed rating

apps/courses/serializers.py, apps/courses/typing.py, apps/courses/views.py
Дополнительно запросы оптимизированы, дока дополнена валидным примером response.
=> Fix бага с неправильным подсчетом и выдачей результата по текущему заданию.

apps/courses/views.py
=> fixed stats

apps/courses/serializers.py, apps/courses/views.py
1. Добавлен description в роут со всеми навыками
2. Захардкодил статичный 1 уровень для навыкам (потом надо исправить)
=> description для навыков, статичный уровень для навыков

apps/courses/serializers.py, apps/courses/views.py
Но необходимо отрефакторить вью класс и сериализаторы,
оптимизировать методы.
=> Добавлены ожидаемые поля

apps/subscription/urls.py, apps/subscription/views.py
=> refund added

apps/subscription/typing.py
=> fix payment

apps/subscription/views.py
=> fix refund

apps/courses/migrations/0009_task_status.py
=> fixed migrations 2

apps/courses/views.py
Скрытые позиции теперь не учитываются при подсчете прогресса.
=> PRO-334: Правки в прогресс юзера

apps/courses/serializers.py, apps/courses/services.py, apps/courses/typing.py, apps/courses/views.py, apps/procollab_skills/celery.py, apps/progress/managers.py, apps/progress/models.py, apps/progress/serializers.py, apps/progress/services.py, apps/progress/tasks.py, apps/progress/typing.py, apps/progress/urls.py, apps/progress/views/profile.py
Профиль пользователя:
1. На роут `/progress/profile/` выведена информация согласно требованиям и дизайну в фигме. 
`user_data` - добавлено общее кол-во поинтов пользователя за все время. 
`skills` - массив с данными по навыкам пользователя, в нем `skill_progress` - % комплита навыка. 
(в последствии, когда будет выбор из 5шт. на месяц будет чуть переработан)
`months` - месяцы и успешное их завершение (только те, на которые выпадала подписка) 
Например, сейчас Август, подписка была куплена в июле, то в ответе будет Июль, в Сентябре появится Август. Результата по месяцам, когда пользователь не был подписан, нет в результирующем массиве (если есть необходимость добавить, прошу сообщить). 
`successfully_done` у месяца может быть `true`/`false` - успешно/не успешно завершен. 
Пример Response: …
=> PRO-358: Прогресс пользователя

apps/courses/services.py
На проде все задания - 1 неделя.
В выдаче сейчас находится все что доступно пользователю. Соотв. если доступна 3 неделя, а для нее нет заданий, статистика может быть некорректной.
=> PRO-403: Временная мера для недель

apps/progress/filters.py, apps/progress/views/rating.py
изменил в рейтинге показ баллов только для выбранных навыков на все навыки 
(и капельку отрефачил код)
=> fixed bug with rating

apps/progress/filters.py
=> delete users without rating from rating

apps/courses/serializers.py
=> fix bug skills done

apps/progress/admin.py
=> fix seriaizer 3

apps/subscription/serializers.py
=> fix seriaizer 4

apps/progress/admin.py, apps/subscription/serializers.py
=> fix seriaizer 5

apps/progress/models.py
=> fixed models

apps/progress/models.py
=> fixed models1

apps/subscription/tasks.py, apps/subscription/views.py
=> Resub users

apps/subscription/tests.py, apps/subscription/tests/fixtures.py, apps/subscription/tests/test_view_subscription.py, apps/subscription/urls.py, poetry.lock, pyproject.toml
=> added tests for subscription view

apps/subscription/views.py
=> fix subscription bug

apps/tests/conftest.py, apps/tests/courses_tests/constants.py, apps/tests/courses_tests/test_courses_paths.py, apps/tests/fixtures/coureses.py, apps/tests/fixtures/files.py, apps/tests/fixtures/subscription.py, apps/tests/fixtures/users.py, apps/tests/subscription_tests/test_view_subscription.py
Рефакторинг тестов. Все path приложения courses покрыты тестами.
=> Unit tests

apps/questions/tests/fixtures/common.py, apps/questions/tests/fixtures/fixture_connect.py, apps/questions/tests/fixtures/fixtures_exlude.py, apps/questions/tests/fixtures/fixtures_infoslide.py, apps/questions/tests/fixtures/fixtures_single.py, apps/questions/tests/fixtures/fixtures_write.py, apps/questions/tests/test_questions/test_connect.py, apps/questions/tests/test_questions/test_exclude.py, apps/questions/tests/test_questions/test_infoslide.py, apps/questions/tests/test_questions/test_single.py, apps/questions/tests/test_questions/test_write.py, apps/questions/tests/test_sub_outdated.py
=> added tests for questions

apps/courses/admin.py, apps/courses/services.py, apps/courses/tests.py, apps/pytest.ini, apps/subscription/views.py, apps/tests/courses_tests/constants.py, apps/tests/courses_tests/test_courses_response.py, apps/tests/fixtures/coureses.py, apps/tests/fixtures/files.py, apps/tests/fixtures/users.py, apps/tests/subscription_tests/test_view_subscription.py, docker-compose.dev-ci.yml, docker-compose.prod-ci.yml
1) Тесты courses response
2) Баг по подсчету прогресса
3) Docker: restart инструкция
=> Тесты, баг, Docker

apps/procollab_skills/settings.py, apps/procollab_skills/urls.py, apps/questions/admin.py, poetry.lock, pyproject.toml
Reverts PROCOLLAB-github/skills_api#146
=> Revert "Feature/text redact"

apps/procollab_skills/settings.py, apps/questions/admin.py, apps/questions/models/questions.py, apps/tests/fixtures/questions/fixtures_connect.py, apps/tests/fixtures/questions/fixtures_write.py, apps/tests/questions_tests/test_connect.py, apps/tests/questions_tests/test_exclude.py, apps/tests/questions_tests/test_infoslide.py, apps/tests/questions_tests/test_single.py, apps/tests/questions_tests/test_write.py, apps/tests/subscription_tests/test_view_subscription.py
Reverts PROCOLLAB-github/skills_api#150
=> Revert "fixed"

Dockerfile, poetry.lock
=> added sub and selectel

apps/courses/managers.py, apps/courses/services.py, apps/courses/views.py, apps/procollab_skills/permissions.py, apps/progress/services.py, apps/progress/tasks.py, apps/subscription/serializers.py, apps/subscription/views.py
superuser и staff имеют полный доступ к навыкам даже без подписки
исправлены баги связанные с прогрессом
=> Sub permission for staff

README.md
Удалил лишние пункты описания запуска проекта
Без тестов
=> Удалил лишние пункты описания запуска проекта

apps/tests/fixtures/users.py, apps/tests/progress_tests/test_progress_response.py
Исправлено ожидаемая дата рождения пользователя
_Исправлен тест в части ожидаемого возраста пользователя в фикстурах_
_Pytest_
=> Исправлено ожидаемая дата рождения пользователя

apps/progress/urls.py, apps/progress/views/profile.py
Реализован ендпоинт для синхронизации данных профиля skills с профилем procollab
Создал локального пользователя в skills в соответствии с пользователем procollab, внёс изменения в данные пользователя procollab, после чего использовал ендпоинт синхронизации. Данные профиля skills обновились в соответствии с данными профиля procollab. 
Временно решения для синхронизации данных профилей. До правок при внесении изменений в профиль procollab они не вносились в профиль skills.
=> Реализован ендпоинт для синхронизации данных профилей

apps/trajectories/serializers.py
_В сериализатор Траектории добавлены поля с названием и цветами компании_
=> Добавлены поля с информацией о компании в сериализатор траектории

apps/progress/views/profile.py, apps/trajectories/models.py, apps/trajectories/serializers.py, apps/trajectories/urls.py, apps/trajectories/views.py
Реализован ендпоинт для получения учеников и их данных для ментора,
В ендпоинт user-data добавлено поле mentor
Ручное тестирование + имеющиеся тесты.
Обращение к url trajectories/mentor/students
Далее будет необходимо добавить отображение выполненных и просроченных скилов.
=> Добавлен ендпоинт для получения данных о учениках ментора

apps/trajectories/permissions.py, apps/trajectories/serializers.py, apps/trajectories/views.py
Добавлена проверка наличия подписки при попытке активировать траекторию или открыть свою активную траекторию
Создание нового пользователя. Попытка открыть собственную траекторию или активировать траекторию. Без подписки доступа нет. При получении подписки доступ открывается. 
Нет проверки на конкретный тип подписки, на данном этапе предполагается, что подписка будет только одна. Далее есть идея реализовать несколько видов подписок, нужно будет дорабатывать проверки.
=> Добавлена проверка наличия подписки при активации Траектории

apps/courses/serializers.py, apps/tests/courses_tests/constants.py, apps/trajectories/serializers.py
Исправлены поля в SkillDetailsSerializer, StudentSerializer по просьбе frontend-разработчика
SkillDetailsSerializer
"skill_name" ->"name",
"file" -> "file_link",
"level" -> "quantity_of_levels",
StudentSerializer
новое поле "id"
новое поле "specialization"
Переработаны тесты в соответствии с изменениями названий полей
=> Исправлены поля в SkillDetailsSerializer, StudentSerializer, тесты

apps/courses/serializers.py, apps/tests/courses_tests/constants.py
В сериализатор SkillDetailsSerializer добавлено поле ID
Тесты исправлены в соответствии с правками сериализатора
=> В сериализатор SkillDetailsSerializer добавлено поле ID

apps/trajectories/serializers.py
_Внёс в сериализатор TrajectorySerializer поле duration_months._
=> Внёс в сериализатор trajectories поле с общим числом месяцев

apps/trajectories/models.py, apps/trajectories/validators.py
_Добавлены: валидатор HEX цветов, валидатор позитивных чисел длительности у модели Траектории_
=> Добавлены валидаторы цветов и чисел для моделей Траектории и Месяца

apps/courses/admin.py, apps/trajectories/admin.py, apps/trajectories/apps.py, apps/trajectories/models.py, apps/trajectories/serializers.py, apps/trajectories/signals.py, apps/trajectories/validators.py
Добавлена возможность поиска в админ панели по полям "Ментор" при создании траектории и пользовательской траектории
Добавлена возможность сортировать месяца по траектории к которой они относятся
Убрана возможность изменять значение "Пользовательская траектория" при редактировании "Встречи"
Встречи создаются автоматически при создании пользовательской траектории. 
Изменён TrajectoryIdSerializer некорректное название user_trajectory_id заменено на trajectory_id
Реализованы валидатор для HEX цветов при создании "Траектории"
Добавлен валидатор позитивных чисел длительности у модели Траектории
=> Оптимизация административной панели

apps/questions/mapping.py, apps/questions/services/check_questions_answers.py, apps/tests/courses_tests/test_courses_response.py, apps/tests/fixtures/skill_answers.py, apps/tests/progress_tests/test_progress_response.py
=> Исправлено количество баллов начисляемых за платную решённую задачу

apps/progress/mapping.py, apps/questions/mapping.py, apps/questions/services/check_questions_answers.py, apps/tests/courses_tests/test_courses_response.py, apps/tests/fixtures/skill_answers.py, apps/tests/progress_tests/test_progress_response.py
- Баллы за выполненный месяц больше не начисляются;
- Количество бонусных баллов за вовремя выполненный навык изменено с 50 на 20;
- В тестах изменено начисляемое число баллов в соответствии с новой логикой проекта.
=> Изменена система начисления баллов

apps/courses/serializers.py, apps/tests/courses_tests/constants.py
=> В all-skills добавлены поля "is_from_trajectory" "requires_subscription" 
